export const allCourses: {
  name: string;
  type:
    | "Balboa"
    | "Lindy Hop"
    | "St. Louis Shag"
    | "Collegiate Shag"
    | "Charleston"
    | "Tap Dance"
    | "Solo Jazz"
    | "SlowBal"
    | "Party";
  day: "Friday" | "Saturday" | "Sunday";
  number?: string;
  level?: string;
  teachers?: string;
  time: string;
  place?: string;
}[] = [
  {
    number: "Nr. 01",
    name: "Slow Down Your Flow",
    level: "INT/ADV",
    teachers: "Lenka & Jirka",
    type: "Balboa",
    day: "Friday",
    time: "12:15 - 13:45",
    place: undefined,
  },
  {
    number: "Nr. 02",
    name: "Jig Walk",
    level: "BEG",
    teachers: "Gaby & Nathan",
    type: "Lindy Hop",
    day: "Friday",
    time: "12:15 - 13:45",
    place: undefined,
  },
  {
    number: "Nr. 03",
    name: "Quick Redirections",
    level: "INT/ADV",
    teachers: "Míša & Štěpán",
    type: "Lindy Hop",
    day: "Friday",
    time: "14:00 - 15:30",
    place: undefined,
  },
  {
    number: "Nr. 04",
    name: "Charleston Transitions",
    level: "INT",
    teachers: "Gaby & Nathan",
    type: "Charleston",
    day: "Friday",
    time: "14:00 - 15:30",
    place: undefined,
  },
  {
    number: "Nr. 05",
    name: "Spin and Barrel Roll Around the Floor",
    level: "INT/ADV",
    teachers: "Charlotte & Jordan",
    type: "Collegiate Shag",
    day: "Friday",
    time: "15:45 - 17:15",
    place: undefined,
  },
  {
    number: "Nr. 06",
    name: "Sugar Push",
    level: "INT",
    teachers: "Lenka & Jirka",
    type: "Lindy Hop",
    day: "Friday",
    time: "15:45 - 17:15",
    place: undefined,
  },
  {
    number: "Nr. 07",
    name: "SlowBal in Dean Raftery Style",
    level: "BEG/INT",
    teachers: "Míša & Štěpán",
    type: "SlowBal",
    day: "Friday",
    time: "17:30 - 19:00",
    place: undefined,
  },
  {
    number: "Nr. 08",
    name: "Solo Jazz Routine",
    level: "ALL levels",
    teachers: "Gaby & Nathan",
    type: "Solo Jazz",
    day: "Friday",
    time: "17:30 - 19:00",
    place: undefined,
  },
  {
    name: "Friday party",
    type: "Party",
    day: "Friday",
    time: "20:00 - 02:00",
    place: undefined,
  },

  {
    number: "Nr. 09",
    name: "Kicks 101",
    level: "INT",
    teachers: "Charlotte & Jordan",
    type: "Collegiate Shag",
    day: "Saturday",
    time: "10:30 - 12:00",
    place: undefined,
  },
  {
    number: "Nr. 10",
    name: "PureBal in Dean Raftery Style",
    level: "ADV",
    teachers: "Míša & Štěpán",
    type: "Balboa",
    day: "Saturday",
    time: "10:30 - 12:00",
    place: undefined,
  },
  {
    number: "Nr. 11",
    name: "Slowing Down and Redirections",
    level: "INT",
    teachers: "Míša & Štěpán",
    type: "Balboa",
    day: "Saturday",
    time: "12:15 - 13:45",
    place: undefined,
  },
  {
    number: "Nr. 12",
    name: "Stop Hesitating",
    level: "ADV",
    teachers: "Charlotte & Jordan",
    type: "Collegiate Shag",
    day: "Saturday",
    time: "12:15 - 13:45",
    place: undefined,
  },
  {
    number: "Nr. 13",
    name: "Technique and Flow",
    level: "BEG/INT",
    teachers: "Gaby & Nathan",
    type: "Lindy Hop",
    day: "Saturday",
    time: "12:15 - 13:45",
    place: undefined,
  },
  {
    number: "Nr. 14",
    name: "Advanced Steps From Old Movies",
    level: "ADV",
    teachers: "Gaby & Nathan",
    type: "Lindy Hop",
    day: "Saturday",
    time: "14:00 - 15:30",
    place: undefined,
  },
  {
    number: "Nr. 15",
    name: "Up and Down",
    level: "INT",
    teachers: "Charlotte & Jordan",
    type: "Lindy Hop",
    day: "Saturday",
    time: "14:00 - 15:30",
    place: undefined,
  },
  {
    number: "Nr. 16",
    name: "Slows and Quicks",
    level: "BEG",
    teachers: "Lenka & Jirka",
    type: "Collegiate Shag",
    day: "Saturday",
    time: "14:00 - 15:30",
    place: undefined,
  },
  {
    number: "Nr. 17",
    name: "Leaders Style",
    level: "ALL levels",
    teachers: "Nathan",
    type: "Lindy Hop",
    day: "Saturday",
    time: "15:45 - 17:15",
    place: undefined,
  },
  {
    number: "Nr. 18",
    name: "Followers Technique",
    level: "INT/ADV",
    teachers: "Gaby",
    type: "Lindy Hop",
    day: "Saturday",
    time: "15:45 - 17:15",
    place: undefined,
  },
  {
    number: "Nr. 19",
    name: "Shag Out!",
    level: "BEG/INT",
    teachers: "Lenka & Jirka",
    type: "St. Louis Shag",
    day: "Saturday",
    time: "15:45 - 17:15",
    place: undefined,
  },
  {
    number: "Nr. 20",
    name: "Teaser: Try to Tap It!",
    level: "ALL levels",
    teachers: "Kamila",
    type: "Tap Dance",
    day: "Saturday",
    time: "17:30 - 19:00",
    place: undefined,
  },
  {
    name: "Saturday party",
    type: "Party",
    day: "Saturday",
    time: "20:00 - 02:00",
    place: undefined,
  },

  {
    number: "Nr. 21",
    name: "Creative Partnering",
    level: "ADV",
    teachers: "Gaby & Nathan",
    type: "Lindy Hop",
    day: "Sunday",
    time: "10:30 - 12:00",
    place: undefined,
  },
  {
    number: "Nr. 22",
    name: "Slide Combos",
    level: "BEG/INT",
    teachers: "Charlotte & Jordan",
    type: "Lindy Hop",
    day: "Sunday",
    time: "10:30 - 12:00",
    place: undefined,
  },
  {
    number: "Nr. 23",
    name: "Single and Double Rhythms",
    level: "INT",
    teachers: "Charlotte & Jordan",
    type: "Collegiate Shag",
    day: "Sunday",
    time: "12:15 - 13:45",
    place: undefined,
  },
  {
    number: "Nr. 24",
    name: "Fancy Moves",
    level: "INT",
    teachers: "Gaby & Nathan",
    type: "Lindy Hop",
    day: "Sunday",
    time: "12:15 - 13:45",
    place: undefined,
  },
  {
    number: "Nr. 25",
    name: "Swing Out! Anytime, Anywhere!",
    level: "ADV",
    teachers: "Lenka & Jirka",
    type: "Lindy Hop",
    day: "Sunday",
    time: "12:15 - 13:45",
    place: undefined,
  },
  {
    number: "Nr. 26",
    name: "Sailor-Barrel Combo",
    level: "INT/ADV",
    teachers: "Lenka & Jirka",
    type: "St. Louis Shag",
    day: "Sunday",
    time: "14:00 - 15:30",
    place: undefined,
  },
  {
    number: "Nr. 27",
    name: "Breaking Down Venice Beach Moves",
    level: "INT/ADV",
    teachers: "Gaby & Nathan",
    type: "Balboa",
    day: "Sunday",
    time: "14:00 - 15:30",
    place: undefined,
  },
  {
    number: "Nr. 28",
    name: "„Wa-Dam“ Favorite Rhythm Change",
    level: "BEG",
    teachers: "Míša & Štěpán",
    type: "Balboa",
    day: "Sunday",
    time: "14:00 - 15:30",
    place: undefined,
  },
];
